<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ConfiguracionProductos.aspx.cs" Inherits="Vistas.ConfiguracionProductos" %>

<!DOCTYPE html>
<link href="Css/EstiloPaginas.css" rel="stylesheet" type="text/css" />
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            font-size: x-large;
            width: 428px;
            height: 45px;
        }
        .auto-style3 {
            width: 428px;
        }
        .auto-style4 {
            height: 45px;
        }
        .auto-style5 {
            width: 428px;
            height: 31px;
        }
        .auto-style6 {
            height: 31px;
        }
        .auto-style7 {
            height: 45px;
            width: 295px;
        }
        .auto-style8 {
            height: 31px;
            width: 295px;
        }
        .auto-style9 {
            width: 295px;
        }
        .auto-style10 {
            margin-right: 76px;
        }
        .auto-style11 {
            font-size: large;
        }
        .auto-style17 {
            font-size: small;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="auto-style1">
            <tr>
                <td class="auto-style2"><strong>CONFIGURACION PRODUCTOS</strong></td>
                <td class="auto-style7">
                        <strong>
                        <asp:Image ID="imgUsuario" runat="server" Height="45px" Width="45px" Visible="False" />
                        <asp:Label ID="lblUsuarioLogeado" runat="server" CssClass="auto-style11"></asp:Label>
                        </strong>
                    </td>
                <td class="auto-style4">
                        &nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style5">
                    <strong>
                    <asp:HyperLink ID="hlAgregarProducto" runat="server" NavigateUrl="~/AgregarProductos.aspx" CssClass="auto-style11">Agregar producto</asp:HyperLink>
                    </strong>
                </td>
                <td class="auto-style8">
                    <strong>
            <asp:HyperLink ID="hlHome" runat="server" NavigateUrl="~/PaginaPrincipal.aspx" CssClass="auto-style11">Home</asp:HyperLink>
                    </strong>
                </td>
                <td class="auto-style6">
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style9">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3"><strong><span class="auto-style11">Buscar por nombre:&nbsp;</span>&nbsp;</strong>&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="txtFiltroBuscar" class="txtBox" runat="server" Width="178px"></asp:TextBox>
                </td>
                <td class="auto-style9"><asp:Button ID="btnBuscar" class="btn neutro" runat="server" Text="Buscar" OnClick="btnBuscar_Click" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="btnBorrar" class="btn neutro" runat="server" OnClick="btnBorrar_Click" Text="Borrar Filtro" />
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">
                    <asp:Label ID="lblMensaje"  class="validacion" runat="server"></asp:Label>
                </td>
                <td class="auto-style9">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">
                    <asp:Button ID="btnConfirmar" class="btn neutro" runat="server" OnClick="btnConfirmar_Click" Text="Confirmar" Visible="False" />
&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnCancelar" class="btn neutro" runat="server" OnClick="btnCancelar_Click" Text="Cancelar" Visible="False" />
                </td>
                <td class="auto-style9">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <div>
            <asp:GridView ID="gvTablaProductos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnRowCancelingEdit="gvTablaProductos_RowCancelingEdit" OnRowDeleting="gvTablaProductos_RowDeleting" OnRowEditing="gvTablaProductos_RowEditing" OnRowUpdating="gvTablaProductos_RowUpdating" OnRowDataBound="gvTablaProductos_RowDataBound" AllowPaging="True" OnPageIndexChanging="gvTablaProductos_PageIndexChanging" CssClass="auto-style10" Width="1153px">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="Codigo">
                        <EditItemTemplate>
                            <asp:Label ID="lblCodProducto" runat="server" Text='<%# Bind("CodProducto_Pro") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCodProducto" runat="server" Text='<%# Bind("CodProducto_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtNombreProducto" runat="server" Text='<%# Bind("Nombre_Pro") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtNombreProducto">Ingrese un nombre</asp:RequiredFieldValidator>
                            <br />
                            <asp:Label ID="lblMensajeNombre" runat="server"></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombreProd" runat="server" Text='<%# Bind("Nombre_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Categoría">
                        <EditItemTemplate>
                            <strong>
                            <asp:Label ID="lblCategoriaEdit" runat="server" Text='<%# Bind("Nombre_Ca") %>'></asp:Label>
                            </strong>
                            <br />
                            <asp:DropDownList ID="ddlCategorias" runat="server">
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator ID="rfvCategoria" runat="server" ControlToValidate="ddlCategorias" InitialValue="--Seleccionar--">Selecciona una categoria</asp:RequiredFieldValidator>
                            <br />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCodCategoria" runat="server" Text='<%# Bind("Nombre_Ca") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Sint Tacc">
                        <EditItemTemplate>
                            <asp:RadioButtonList ID="rblSinTacc" runat="server" Width="86px">
                                <asp:ListItem Value="true">Si</asp:ListItem>
                                <asp:ListItem Value="false">No</asp:ListItem>
                            </asp:RadioButtonList>
                            <asp:Label ID="lblSinTacc" runat="server" Text='<%# Bind("SinTacc_Pro") %>' Visible="False"></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblSinTacc" runat="server" Text='<%# Bind("SinTacc_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Stock">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtStock" runat="server" Text='<%# Bind("Stock_Pro") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvStock" runat="server" ControlToValidate="txtStock">Ingrese un stock</asp:RequiredFieldValidator>
                            <br />
                            <asp:RegularExpressionValidator ID="reNumero" runat="server" ControlToValidate="txtStock" ValidationExpression="^\d+$">Ingrese numeros</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblStock" runat="server" Text='<%# Bind("Stock_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio x Unidad">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPrecio" runat="server" Text='<%# Bind("PrecioUnitario_Pro") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvPrecio" runat="server" ControlToValidate="txtPrecio">Ingrese un precio</asp:RequiredFieldValidator>
                            <br />
                            <asp:RegularExpressionValidator ID="reNumeroPrecio" runat="server" ControlToValidate="txtPrecio" ValidationExpression="^\d+([.,]\d{1,2})?$">Ingrese numeros</asp:RegularExpressionValidator>
                            <br />
                            <asp:Label ID="lblMensajePrecio" runat="server" CssClass="auto-style17" Text="Los decimales deben de ser ingresados con coma (,)"></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioxUnidad" runat="server" Text='<%# Bind("PrecioUnitario_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Imagen">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtImagen" runat="server" Text='<%# Bind("Imagen_Pro") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvImagen" runat="server" ControlToValidate="txtImagen">Ingrese un url</asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblImagen" runat="server" Text='<%# Bind("Imagen_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <EditItemTemplate>
                            <asp:RadioButtonList ID="rblEstado" runat="server" SelectedValue='<%# Bind("Estado_Pro") %>' Width="86px">
                                <asp:ListItem Text="True" Value="True" />
                                <asp:ListItem Text="False" Value="False" />
                            </asp:RadioButtonList>
                            <asp:Label ID="lblEstado" runat="server" Text='<%# Bind("Estado_Pro") %>' Visible="False"></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblEstadoP" runat="server" Text='<%# Bind("Estado_Pro") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>
            <br />
            <strong>
                    <asp:HyperLink ID="hlVolver" runat="server" NavigateUrl="~/PerfilAdministrador.aspx" CssClass="auto-style11">Volver</asp:HyperLink>
                </strong>
        </div>
    </form>
</body>
</html>
